### ISSUE TITLE
how to guide

### ISSUE THREAD

**Issue by mbirdi** [MariaNattestad/old_python_splitthreader#1]
@SplitThreader

I attended the talk at PyData and found the project interesting.  I was looking thru the code and I had a couple of questions.  Is there a how-to guide on how to install and use the code?  One thing I was confused about was these are python scripts which will operate on a dataset of genomic information.  But it was a little unclear to me where that data resides.  Can you add a data folder with a couple of made up genes or genes in the public domain?  Maybe a data folder with psuedo-data if the actual data can not be made available.  

I enjoyed the talk!

Thanks!

**Comment by MariaNattestad** [comment]
Turns out I can't share the code because this is my thesis project, but I
started a very related project that more biologists can actually benefit
from:
https://github.com/MariaNattestad/assemblygraphvis
The test data for this will be up in a few days once I hear back from
someone who holds permission for the data. I will create a video describing
the problem if people are interested in contributing.

Thanks!
Maria
